In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
airbnb=pd.read_csv("C:\\Arvind Files\\ML PROJECT FILES\\new-york-city-airbnb-open-data\\AB_NYC_2019.csv",engine='python')

In [4]:
airbnb.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [5]:
airbnb['name'].value_counts()

Hillside Hotel                                        18
Home away from home                                   17
New york Multi-unit building                          16
Brooklyn Apartment                                    12
Loft Suite @ The Box House Hotel                      11
Private Room                                          11
Private room                                          10
Artsy Private BR in Fort Greene Cumberland            10
Private room in Brooklyn                               8
Cozy Brooklyn Apartment                                8
Private room in Williamsburg                           8
Beautiful Brooklyn Brownstone                          8
Harlem Gem                                             7
Home Away From Home                                    6
Cozy Room                                              6
New York Apartment                                     6
Cozy East Village Apartment                            6
Private room in Manhattan                              6
Bushwick Oasis                                         6
IN MINT CONDITION-STUDIOS EAST 44TH/UNITED NATIONS     6
Home Sweet Home                                        6
West Village Apartment                                 6
East Village Apartment                                 5
Cozy Apartment                                         5
Harlem Oasis                                           5
Home                                                   5
Private Room in Brooklyn                               5
Cozy Private Room                                      5
Cozy home away from home                               5
A CLASSIC NYC NEIGHBORHOOD-EAST 86TH/5TH AVENUE        5
                                                      ..
Sunlit Fabulous "Treehouse" in Greenwich Village       1
Upper West Side Luxury Rental                          1
Mins to Manhattan and Williamsburg!                    1
The Bronx's Oasis                                      1
Immaculate, bright, private lofted room in W-Burg      1
Beautiful spacious Loft , east village,2 real beds     1
Garden Duplex in Clinton Hill                          1
Spacious, sun-filled apartment in family townhome      1
Beautiful, High-Ceiling Apartment in Fort Greene       1
Charming West Village Pad                              1
East Village Bedroom for Rent                          1
Central Park, Museum Mile                              1
1BDR - Hell's Kitchen Hideaway                         1
Luxury High Floor Studio with stunning view            1
Cozy UWS Studio by Central Park                        1
Sunny Room in Heart Of Bushwick Jefferson L train      1
Private Bamboo Garden Studio                           1
Room for Female in NoHo/EastVillage                    1
Brooklyn Bedroom (Flatbush-Ditmas)                     1
Sonder | Stock Exchange | Upscale 1BR + Sofa Bed       1
Large room in new Williamsburg apartment               1
Modern Spacious Room in Loft with Rooftop              1
Elegant SOHO One Bedroom                               1
Eclectic Prime Williamsburg Space                      1
1 Large Bedroom plus 2nd bed                           1
1 Bed in a Lux Apt on Wall Street                      1
Akua's Bed-Stuy Study                                  1
Beautiful&New Bedrooms near everything you want!       1
Newly renovated private room close to Central Park     1
Sunny Lower E. Side Ap. near BDFMJZ                    1
Name: name, Length: 47905, dtype: int64

In [6]:
airbnb['host_name'].value_counts()

Michael               417
David                 403
Sonder (NYC)          327
John                  294
Alex                  279
Blueground            232
Sarah                 227
Daniel                226
Jessica               205
Maria                 204
Mike                  194
Andrew                190
Anna                  187
Laura                 182
Chris                 182
Melissa               160
Emily                 157
Jennifer              154
James                 151
Rachel                146
Kara                  143
Amy                   142
Jonathan              142
Michelle              140
Jason                 140
Brian                 140
Adam                  139
Mark                  139
Ben                   135
Anthony               134
                     ...
Erina                   1
Agathe Et Francois      1
Natassha                1
Tuana                   1
Kham                    1
Mayrav                  1
Kate And Jason          1
Lyra                    1
Catia                   1
Darlena                 1
Khatia                  1
Cristiana               1
Lani                    1
Ohran                   1
Danie                   1
Andres&Ine              1
Sonskeshana             1
Lai-Lin                 1
Ana Y Hugo              1
Roshelle                1
Ilo And Richard         1
Pierre Yves             1
Yassmina                1
Yamid                   1
Awa                     1
Parth                   1
Sheneque                1
Na'Im                   1
Prangchat               1
Adila                   1
Name: host_name, Length: 11452, dtype: int64

In [7]:
airbnb['room_type'].value_counts()

Entire home/apt    25409
Private room       22326
Shared room         1160
Name: room_type, dtype: int64

In [8]:
airbnb['minimum_nights'].value_counts()

1       12720
2       11696
3        7999
30       3760
4        3303
5        3034
7        2058
6         752
14        562
10        483
29        340
15        279
20        223
28        203
31        201
21        135
8         130
60        106
90        104
12         91
25         82
9          80
13         54
180        43
11         33
45         32
365        29
18         28
120        28
16         18
        ...
198         1
480         1
36          1
134         1
58          1
250         1
400         1
185         1
153         1
184         1
183         1
87          1
182         1
85          1
275         1
370         1
114         1
175         1
39          1
222         1
366         1
122         1
299         1
43          1
74          1
42          1
186         1
265         1
1000        1
364         1
Name: minimum_nights, Length: 109, dtype: int64